// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Message.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type USER struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IPPort               []byte   `protobuf:"bytes,2,opt,name=IPPort,proto3" json:"IPPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *USER) Reset()         { *m = USER{} }
func (m *USER) String() string { return proto.CompactTextString(m) }
func (*USER) ProtoMessage()    {}
func (*USER) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{0}
}
func (m *USER) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_USER.Unmarshal(m, b)
}
func (m *USER) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_USER.Marshal(b, m, deterministic)
}
func (dst *USER) XXX_Merge(src proto.Message) {
	xxx_messageInfo_USER.Merge(dst, src)
}
func (m *USER) XXX_Size() int {
	return xxx_messageInfo_USER.Size(m)
}
func (m *USER) XXX_DiscardUnknown() {
	xxx_messageInfo_USER.DiscardUnknown(m)
}

var xxx_messageInfo_USER proto.InternalMessageInfo

func (m *USER) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *USER) GetIPPort() []byte {
	if m != nil {
		return m.IPPort
	}
	return nil
}

type MsgHead struct {
	Typ                  uint32   `protobuf:"fixed32,1,opt,name=Typ" json:"Typ,omitempty"`
	BodyLen              uint32   `protobuf:"fixed32,2,opt,name=BodyLen" json:"BodyLen,omitempty"`
	Blocks               uint32   `protobuf:"fixed32,3,opt,name=Blocks" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHead) Reset()         { *m = MsgHead{} }
func (m *MsgHead) String() string { return proto.CompactTextString(m) }
func (*MsgHead) ProtoMessage()    {}
func (*MsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{1}
}
func (m *MsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHead.Unmarshal(m, b)
}
func (m *MsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHead.Marshal(b, m, deterministic)
}
func (dst *MsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHead.Merge(dst, src)
}
func (m *MsgHead) XXX_Size() int {
	return xxx_messageInfo_MsgHead.Size(m)
}
func (m *MsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHead proto.InternalMessageInfo

func (m *MsgHead) GetTyp() uint32 {
	if m != nil {
		return m.Typ
	}
	return 0
}

func (m *MsgHead) GetBodyLen() uint32 {
	if m != nil {
		return m.BodyLen
	}
	return 0
}

func (m *MsgHead) GetBlocks() uint32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

type MsgAck struct {
	IPPort               []byte   `protobuf:"bytes,1,opt,name=IPPort,proto3" json:"IPPort,omitempty"`
	Name                 []byte   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ClientsNum           uint32   `protobuf:"varint,3,opt,name=ClientsNum" json:"ClientsNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAck) Reset()         { *m = MsgAck{} }
func (m *MsgAck) String() string { return proto.CompactTextString(m) }
func (*MsgAck) ProtoMessage()    {}
func (*MsgAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{2}
}
func (m *MsgAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAck.Unmarshal(m, b)
}
func (m *MsgAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAck.Marshal(b, m, deterministic)
}
func (dst *MsgAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAck.Merge(dst, src)
}
func (m *MsgAck) XXX_Size() int {
	return xxx_messageInfo_MsgAck.Size(m)
}
func (m *MsgAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAck proto.InternalMessageInfo

func (m *MsgAck) GetIPPort() []byte {
	if m != nil {
		return m.IPPort
	}
	return nil
}

func (m *MsgAck) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MsgAck) GetClientsNum() uint32 {
	if m != nil {
		return m.ClientsNum
	}
	return 0
}

type MsgBody struct {
	User                 *USER    `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBody) Reset()         { *m = MsgBody{} }
func (m *MsgBody) String() string { return proto.CompactTextString(m) }
func (*MsgBody) ProtoMessage()    {}
func (*MsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{3}
}
func (m *MsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBody.Unmarshal(m, b)
}
func (m *MsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBody.Marshal(b, m, deterministic)
}
func (dst *MsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBody.Merge(dst, src)
}
func (m *MsgBody) XXX_Size() int {
	return xxx_messageInfo_MsgBody.Size(m)
}
func (m *MsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBody proto.InternalMessageInfo

func (m *MsgBody) GetUser() *USER {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *MsgBody) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type FileBody struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName" json:"FileName,omitempty"`
	Chunked              []byte   `protobuf:"bytes,2,opt,name=Chunked,proto3" json:"Chunked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileBody) Reset()         { *m = FileBody{} }
func (m *FileBody) String() string { return proto.CompactTextString(m) }
func (*FileBody) ProtoMessage()    {}
func (*FileBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{4}
}
func (m *FileBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileBody.Unmarshal(m, b)
}
func (m *FileBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileBody.Marshal(b, m, deterministic)
}
func (dst *FileBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileBody.Merge(dst, src)
}
func (m *FileBody) XXX_Size() int {
	return xxx_messageInfo_FileBody.Size(m)
}
func (m *FileBody) XXX_DiscardUnknown() {
	xxx_messageInfo_FileBody.DiscardUnknown(m)
}

var xxx_messageInfo_FileBody proto.InternalMessageInfo

func (m *FileBody) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileBody) GetChunked() []byte {
	if m != nil {
		return m.Chunked
	}
	return nil
}

type FileM struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName" json:"FileName,omitempty"`
	FileTempName         string   `protobuf:"bytes,2,opt,name=FileTempName" json:"FileTempName,omitempty"`
	User                 *USER    `protobuf:"bytes,3,opt,name=User" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileM) Reset()         { *m = FileM{} }
func (m *FileM) String() string { return proto.CompactTextString(m) }
func (*FileM) ProtoMessage()    {}
func (*FileM) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{5}
}
func (m *FileM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileM.Unmarshal(m, b)
}
func (m *FileM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileM.Marshal(b, m, deterministic)
}
func (dst *FileM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileM.Merge(dst, src)
}
func (m *FileM) XXX_Size() int {
	return xxx_messageInfo_FileM.Size(m)
}
func (m *FileM) XXX_DiscardUnknown() {
	xxx_messageInfo_FileM.DiscardUnknown(m)
}

var xxx_messageInfo_FileM proto.InternalMessageInfo

func (m *FileM) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileM) GetFileTempName() string {
	if m != nil {
		return m.FileTempName
	}
	return ""
}

func (m *FileM) GetUser() *USER {
	if m != nil {
		return m.User
	}
	return nil
}

type MessageB struct {
	Head                 []byte   `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageB) Reset()         { *m = MessageB{} }
func (m *MessageB) String() string { return proto.CompactTextString(m) }
func (*MessageB) ProtoMessage()    {}
func (*MessageB) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_290086b7f52897f3, []int{6}
}
func (m *MessageB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageB.Unmarshal(m, b)
}
func (m *MessageB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageB.Marshal(b, m, deterministic)
}
func (dst *MessageB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageB.Merge(dst, src)
}
func (m *MessageB) XXX_Size() int {
	return xxx_messageInfo_MessageB.Size(m)
}
func (m *MessageB) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageB.DiscardUnknown(m)
}

var xxx_messageInfo_MessageB proto.InternalMessageInfo

func (m *MessageB) GetHead() []byte {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MessageB) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*USER)(nil), "main.USER")
	proto.RegisterType((*MsgHead)(nil), "main.MsgHead")
	proto.RegisterType((*MsgAck)(nil), "main.MsgAck")
	proto.RegisterType((*MsgBody)(nil), "main.MsgBody")
	proto.RegisterType((*FileBody)(nil), "main.FileBody")
	proto.RegisterType((*FileM)(nil), "main.FileM")
	proto.RegisterType((*MessageB)(nil), "main.MessageB")
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor_Message_290086b7f52897f3) }

var fileDescriptor_Message_290086b7f52897f3 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x6b, 0xbb, 0x40,
	0x10, 0x25, 0x89, 0xbf, 0x98, 0xcc, 0x2f, 0x81, 0xb2, 0x87, 0x22, 0x3d, 0x84, 0xb2, 0xa7, 0x9e,
	0x3c, 0xd8, 0x2f, 0xd0, 0x2a, 0x2d, 0x2d, 0xd4, 0x20, 0x5b, 0xf3, 0x01, 0xb6, 0x71, 0xb1, 0xe2,
	0x9f, 0x15, 0xd7, 0x1c, 0xfc, 0xf6, 0x65, 0xa6, 0xba, 0x58, 0x28, 0xbd, 0xbd, 0x37, 0x3a, 0x6f,
	0xe6, 0xcd, 0x5b, 0xd8, 0xc7, 0xca, 0x18, 0x99, 0x2b, 0xbf, 0xed, 0x74, 0xaf, 0x99, 0x53, 0xcb,
	0xa2, 0xe1, 0x01, 0x38, 0xa7, 0xf7, 0x27, 0xc1, 0x18, 0x38, 0x47, 0x59, 0x2b, 0x6f, 0x71, 0xbb,
	0xb8, 0xdb, 0x09, 0xc2, 0xec, 0x1a, 0xd6, 0xaf, 0x49, 0xa2, 0xbb, 0xde, 0x5b, 0x52, 0x75, 0x64,
	0x3c, 0x06, 0x37, 0x36, 0xf9, 0x8b, 0x92, 0x19, 0xbb, 0x82, 0x55, 0x3a, 0xb4, 0xd4, 0xe5, 0x0a,
	0x84, 0xcc, 0x03, 0x37, 0xd4, 0xd9, 0xf0, 0xa6, 0x1a, 0xea, 0x72, 0xc5, 0x44, 0x51, 0x2e, 0xac,
	0xf4, 0xb9, 0x34, 0xde, 0x8a, 0x3e, 0x8c, 0x8c, 0xa7, 0xb0, 0x8e, 0x4d, 0xfe, 0x78, 0x2e, 0x67,
	0x03, 0x17, 0xf3, 0x81, 0x76, 0xb9, 0xe5, 0x6c, 0xb9, 0x03, 0x40, 0x54, 0x15, 0xaa, 0xe9, 0xcd,
	0xf1, 0x52, 0x93, 0xe2, 0x5e, 0xcc, 0x2a, 0x3c, 0xa2, 0x25, 0x71, 0x36, 0x3b, 0x80, 0x73, 0x32,
	0xaa, 0x23, 0xd1, 0xff, 0x01, 0xf8, 0x68, 0xdc, 0x47, 0xd7, 0x82, 0xea, 0xb8, 0x72, 0x22, 0x87,
	0x4a, 0xcb, 0x6c, 0x9c, 0x30, 0x51, 0xfe, 0x00, 0x9b, 0xe7, 0xa2, 0x52, 0xa4, 0x72, 0xf3, 0x8d,
	0xed, 0x95, 0xb6, 0xc2, 0x72, 0x54, 0x88, 0x3e, 0x2f, 0x4d, 0xa9, 0xac, 0xc2, 0x48, 0x79, 0x0e,
	0xff, 0xf0, 0xaf, 0xf8, 0xcf, 0x76, 0x0e, 0x3b, 0xc4, 0xa9, 0xaa, 0x5b, 0xeb, 0x73, 0x2b, 0x7e,
	0xd4, 0xac, 0x89, 0xd5, 0xef, 0x26, 0x78, 0x00, 0x9b, 0x31, 0xdf, 0x10, 0xef, 0x85, 0xe9, 0x4c,
	0x61, 0x52, 0x52, 0x0c, 0x1c, 0xb4, 0x31, 0xdd, 0x10, 0xf1, 0xc7, 0x9a, 0x5e, 0xc2, 0xfd, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x58, 0x61, 0xf8, 0x1a, 0x02, 0x00, 0x00,
}
