// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgHead struct {
	Typ                  uint32   `protobuf:"varint,1,opt,name=Typ" json:"Typ,omitempty"`
	BodyLen              uint32   `protobuf:"varint,2,opt,name=BodyLen" json:"BodyLen,omitempty"`
	Blocks               uint32   `protobuf:"varint,3,opt,name=Blocks" json:"Blocks,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHead) Reset()         { *m = MsgHead{} }
func (m *MsgHead) String() string { return proto.CompactTextString(m) }
func (*MsgHead) ProtoMessage()    {}
func (*MsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_a39cb5bf602d4da3, []int{0}
}
func (m *MsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHead.Unmarshal(m, b)
}
func (m *MsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHead.Marshal(b, m, deterministic)
}
func (dst *MsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHead.Merge(dst, src)
}
func (m *MsgHead) XXX_Size() int {
	return xxx_messageInfo_MsgHead.Size(m)
}
func (m *MsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHead proto.InternalMessageInfo

func (m *MsgHead) GetTyp() uint32 {
	if m != nil {
		return m.Typ
	}
	return 0
}

func (m *MsgHead) GetBodyLen() uint32 {
	if m != nil {
		return m.BodyLen
	}
	return 0
}

func (m *MsgHead) GetBlocks() uint32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *MsgHead) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type AckMsg struct {
	IPPort               []byte   `protobuf:"bytes,1,opt,name=IPPort,proto3" json:"IPPort,omitempty"`
	ClientsNum           uint32   `protobuf:"varint,2,opt,name=ClientsNum" json:"ClientsNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMsg) Reset()         { *m = AckMsg{} }
func (m *AckMsg) String() string { return proto.CompactTextString(m) }
func (*AckMsg) ProtoMessage()    {}
func (*AckMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_a39cb5bf602d4da3, []int{1}
}
func (m *AckMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMsg.Unmarshal(m, b)
}
func (m *AckMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMsg.Marshal(b, m, deterministic)
}
func (dst *AckMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMsg.Merge(dst, src)
}
func (m *AckMsg) XXX_Size() int {
	return xxx_messageInfo_AckMsg.Size(m)
}
func (m *AckMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AckMsg proto.InternalMessageInfo

func (m *AckMsg) GetIPPort() []byte {
	if m != nil {
		return m.IPPort
	}
	return nil
}

func (m *AckMsg) GetClientsNum() uint32 {
	if m != nil {
		return m.ClientsNum
	}
	return 0
}

type BlockMsg struct {
	BlocksNo             uint32   `protobuf:"varint,1,opt,name=BlocksNo" json:"BlocksNo,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMsg) Reset()         { *m = BlockMsg{} }
func (m *BlockMsg) String() string { return proto.CompactTextString(m) }
func (*BlockMsg) ProtoMessage()    {}
func (*BlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_a39cb5bf602d4da3, []int{2}
}
func (m *BlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMsg.Unmarshal(m, b)
}
func (m *BlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMsg.Marshal(b, m, deterministic)
}
func (dst *BlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMsg.Merge(dst, src)
}
func (m *BlockMsg) XXX_Size() int {
	return xxx_messageInfo_BlockMsg.Size(m)
}
func (m *BlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMsg proto.InternalMessageInfo

func (m *BlockMsg) GetBlocksNo() uint32 {
	if m != nil {
		return m.BlocksNo
	}
	return 0
}

func (m *BlockMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MessageB struct {
	Head                 *MsgHead  `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	Body                 *BlockMsg `protobuf:"bytes,2,opt,name=Body" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageB) Reset()         { *m = MessageB{} }
func (m *MessageB) String() string { return proto.CompactTextString(m) }
func (*MessageB) ProtoMessage()    {}
func (*MessageB) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_a39cb5bf602d4da3, []int{3}
}
func (m *MessageB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageB.Unmarshal(m, b)
}
func (m *MessageB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageB.Marshal(b, m, deterministic)
}
func (dst *MessageB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageB.Merge(dst, src)
}
func (m *MessageB) XXX_Size() int {
	return xxx_messageInfo_MessageB.Size(m)
}
func (m *MessageB) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageB.DiscardUnknown(m)
}

var xxx_messageInfo_MessageB proto.InternalMessageInfo

func (m *MessageB) GetHead() *MsgHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MessageB) GetBody() *BlockMsg {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgHead)(nil), "message.MsgHead")
	proto.RegisterType((*AckMsg)(nil), "message.AckMsg")
	proto.RegisterType((*BlockMsg)(nil), "message.BlockMsg")
	proto.RegisterType((*MessageB)(nil), "message.MessageB")
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor_Message_a39cb5bf602d4da3) }

var fileDescriptor_Message_a39cb5bf602d4da3 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x0d, 0x49, 0x99, 0xa6, 0x50, 0xe7, 0x20, 0x8b, 0x07, 0x29, 0x8b, 0x42, 0x4f,
	0x39, 0xd4, 0x3f, 0x50, 0xe3, 0xa5, 0x82, 0x29, 0x61, 0x11, 0x3c, 0xaf, 0xcd, 0x12, 0xa5, 0x69,
	0xb7, 0x74, 0xe2, 0x21, 0xff, 0x5e, 0x76, 0x9c, 0x84, 0xde, 0xe6, 0xdb, 0xd9, 0x79, 0xf3, 0xe6,
	0xc1, 0xbc, 0x74, 0x44, 0xb6, 0x71, 0xf9, 0xf9, 0xe2, 0x3b, 0x8f, 0xe9, 0xf1, 0x1f, 0xb5, 0x85,
	0xb4, 0xa4, 0x66, 0xeb, 0x6c, 0x8d, 0x0b, 0x98, 0x7c, 0xf4, 0x67, 0x15, 0x2d, 0xa3, 0xd5, 0xdc,
	0x84, 0x12, 0x15, 0xa4, 0x85, 0xaf, 0xfb, 0x77, 0x77, 0x52, 0x37, 0xfc, 0x3a, 0x20, 0xde, 0x41,
	0x52, 0xb4, 0x7e, 0x7f, 0x20, 0x35, 0xe1, 0x86, 0x10, 0x22, 0xc4, 0x5b, 0x4b, 0xdf, 0x2a, 0x5e,
	0x46, 0xab, 0xcc, 0x70, 0xad, 0x37, 0x90, 0xbc, 0xec, 0x0f, 0x25, 0x35, 0x61, 0xea, 0xad, 0xaa,
	0xfc, 0xa5, 0xe3, 0x25, 0x99, 0x11, 0xc2, 0x07, 0x80, 0xd7, 0xf6, 0xc7, 0x9d, 0x3a, 0xda, 0xfd,
	0x1e, 0x65, 0xd5, 0xd5, 0x8b, 0xde, 0xc0, 0x94, 0xf5, 0x83, 0xc6, 0xbd, 0xd4, 0xb4, 0xf3, 0x62,
	0x75, 0xe4, 0xe0, 0xb7, 0xb2, 0x7d, 0xeb, 0x6d, 0xcd, 0x22, 0x99, 0x19, 0x50, 0x7f, 0xc2, 0x54,
	0x02, 0x28, 0xf0, 0x11, 0xe2, 0x70, 0x2f, 0x4f, 0xcf, 0xd6, 0x8b, 0x5c, 0xa2, 0xc8, 0x25, 0x07,
	0xc3, 0x5d, 0x7c, 0x82, 0x38, 0x1c, 0xcb, 0x42, 0xb3, 0xf5, 0xed, 0xf8, 0x6b, 0x30, 0x62, 0xb8,
	0xfd, 0x95, 0x70, 0x9e, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xf4, 0x1d, 0x54, 0x60,
	0x01, 0x00, 0x00,
}
